spring:
  profiles:
    group:
      development:
        - "local"
        - "common"
      production:
        - "docker"
        - "common"
    default: "development"

---
spring:
  application:
    name: micro-api
  config:
    activate:
      on-profile: common
  graphql:
    graphiql:
      enabled: true
    schema:
      printer:
        enabled: true
    websocket:
      path: "/graphql"
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  webflux:
    hiddenmethod:
      filter:
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
---
spring:
  config:
    activate:
      on-profile: local
  devtools:
    livereload:
      port: 35219
    restart:
      poll-interval: 1000
  elasticsearch:
    uris:
      - http://localhost:9200
  r2dbc:
    url: r2dbcs:mysql://localhost:3306/cafe?useSSL=false&autoReconnect=true&reWriteBatchedInserts=true
    username: root
    password: root
  redis:
    database: 2
    host: 127.0.0.1
    port: 6379

server:
  http2:
    enabled: true
  port: 9001
  servlet:
    application-display-name: micro-api
logging:
  level:
    root: INFO
    redis:
      clients: TRACE
    web: DEBUG
  file:
    name: micro-api.log
stream:
  key: purchase-events
publish:
  rate: 1000
---
spring:
  config:
    activate:
      on-profile: docker
  redis:
    database: 3
    host: redis
    port: 6379
server:
  http2:
    enabled: true
  port: 9001
  servlet:
    application-display-name: micro-api
logging:
  level:
    root: INFO
    redis:
      clients: TRACE
    web: INFO
  file:
    name: micro-api.log