CREATE TABLE IF NOT EXISTS location
(
  id                 INT UNSIGNED AUTO_INCREMENT  NOT NULL COMMENT '所在地ID',
  code               CHAR(36) UNIQUE              NOT NULL COMMENT '所在地コード',
  name               VARCHAR(256)                 NOT NULL COMMENT '店舗名',
  phone_number       CHAR(13) COMMENT '店舗連絡先(電話番号)',
  mail_address       VARCHAR(256) COMMENT '店舗連絡先(メールアドレス)',
  postal_code        CHAR(7) COMMENT '店舗住所(郵便番号)',
  prefecture_code    TINYINT COMMENT '店舗住所(都道府県コード)',
  address_1          VARCHAR(256) COMMENT '店舗住所(都道府県)',
  address_2          VARCHAR(256) COMMENT '店舗住所(市区町村)',
  address_3          VARCHAR(256) COMMENT '店舗住所(町域)',
  street_address     VARCHAR(256) COMMENT '店舗住所(番地)',
  building_name      VARCHAR(256) COMMENT '店舗住所(建物名)',
  address_supplement VARCHAR(256) COMMENT '店舗住所(補足)',
  open_date          DATE COMMENT '店舗開店日',
  close_date         DATE COMMENT '店舗閉店日',
  opening_time       TIME COMMENT '店舗営業時間(開店時間)',
  closing_time       TIME COMMENT '店舗営業時間(閉店時間)',
  hours_supplement   VARCHAR(256) COMMENT '店舗営業時間(補足)',
  memo               VARCHAR(256) COMMENT '店舗メモ',
  created_date_time  DATETIME                     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '登録日時',
  created_by         INT UNSIGNED                 NOT NULL DEFAULT 0 COMMENT '登録者',
  version            INT UNSIGNED                 NOT NULL DEFAULT 0 COMMENT 'Version',
  updated_date_time  DATETIME                              DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  updated_by         INT UNSIGNED                          DEFAULT NULL COMMENT '更新者',
  deleted_date_time  DATETIME                              DEFAULT NULL COMMENT '削除日時',
  deleted_flag       ENUM ('is_false', 'is_true') NOT NULL DEFAULT 'is_false' COMMENT '論理削除フラグ:is_false-未削除,is_true-削除済',
  PRIMARY KEY (id)
) DEFAULT CHARSET = UTF8MB4 COMMENT '所在地/店舗';