version: '3.8'

services:

  redis:
    build: ./docker-redis
    container_name: docker-redis
    ports:
      - "6379:6379"
    volumes:
      - "./docker-redis/data/:/data"
    hostname: redis
    restart: always
    networks:
      - app-net

  redisinsight:
    build: ./docker-redisinsight
    container_name: docker-redisinsight
    ports:
      - "8001:8001"
    volumes:
      - "./docker-redisinsight/data:/db"
    restart: always
    networks:
      - app-net

networks:
  app-net:
    driver: bridge